
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST";
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS";
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL";

export const ADMIN_LOGOUT = "ADMIN_LOGOUT";


export const ADMIN_FORGOT_PASSWORD_RESET = "ADMIN_FORGOT_PASSWORD_RESET";
export const ADMIN_FORGOT_PASSWORD_REQUEST = "ADMIN_FORGOT_PASSWORD_REQUEST";
export const ADMIN_FORGOT_PASSWORD_SUCCESS = "ADMIN_FORGOT_PASSWORD_SUCCESS";
export const ADMIN_FORGOT_PASSWORD_FAIL = "ADMIN_FORGOT_PASSWORD_FAIL";

export const ADMIN_UPDATE_PROFILE_RESET = "ADMIN_UPDATE_PROFILE_RESET";
export const ADMIN_UPDATE_PROFILE_REQUEST = "ADMIN_UPDATE_PROFILE_REQUEST";
export const ADMIN_UPDATE_PROFILE_SUCCESS = "ADMIN_UPDATE_PROFILE_SUCCESS";
export const ADMIN_UPDATE_PROFILE_FAIL = "ADMIN_UPDATE_PROFILE_FAIL";

export const ADMIN_GET_PROFILE_REQUEST = "ADMIN_GET_PROFILE_REQUEST";
export const ADMIN_GET_PROFILE_SUCCESS = "ADMIN_GET_PROFILE_SUCCESS";
export const ADMIN_GET_PROFILE_FAIL = "ADMIN_GET_PROFILE_FAIL";
