export const ADMIN_SIDEBAR_SHOW = "ADMIN_SIDEBAR_SHOW";
export const ADMIN_SIDEBAR_HIDE = "ADMIN_SIDEBAR_HIDE";

export const ADMIN_SIDEBAR_VERTICAL_SHOW = "ADMIN_SIDEBAR_VERTICAL_SHOW";
export const ADMIN_SIDEBAR_VERTICAL_HIDE = "ADMIN_SIDEBAR_VERTICAL_HIDE";