export const ADMIN_DASHBOARD_COUNT_RESET = "ADMIN_DASHBOARD_COUNT_RESET";
export const ADMIN_DASHBOARD_COUNT_REQUEST = "ADMIN_DASHBOARD_COUNT_REQUEST";
export const ADMIN_DASHBOARD_COUNT_SUCCESS = "ADMIN_DASHBOARD_COUNT_SUCCESS";
export const ADMIN_DASHBOARD_COUNT_FAIL = "ADMIN_DASHBOARD_COUNT_FAIL";